coverage_service: cobertura_xml
xcodeproj: Gini-iOS-SDK.xcodeproj
workspace: Gini-iOS-SDK.xcworkspace
scheme: Gini-iOS-SDK
# simple_output: true
source_directory: Gini-iOS-SDK/
output_directory: Build/Coverage
ignore:
  - ../*
  - Pods/*
