language: objective-c

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet 

before_script:
  - export LANG=en_US.UTF-8
  - ./scripts/install_appledoc.sh
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/appledoc

env:
  - secure: "YI6U3xYnOX+Cox+RNIWMTMCabCKL/K0fvHI5i9O6HYXUfoRO2lPx9/D2kxS0IK9r3eclXoU1ExzbMVHkr5IZdjjuanQKBILR6oodKhDed+cV0JSjVlV7MKSKWajKp4Liv+LHCg6eRf81c7DtBGf+Vy/5nIfMuoavyD/pG+pmfHM="

script:
  - xcodebuild -workspace GiniSDK.xcworkspace -scheme GiniSDKTests -sdk iphonesimulator test
  - xcodebuild -workspace GiniSDK.xcworkspace -scheme Documentation -sdk iphonesimulator build

after_success:
  - ./scripts/publish_docs.sh

