language: objective-c

before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet 

before_script:
  - ./scripts/install_appledoc.sh
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/appledoc

env:
  global:
    - secure: "SXOAf1EohDz7k+qc1sMlhzgMkFpLNcC/awHwZMVJDtb4eiyLsq7WEg9JNe+PmIaYVB/VVU0JbWZgS6OrYjMFBPAozKnIRit/lkTnmljw/pAjHPPP1c0LYwbcIDCkdfvDVZU/45iatiMnda6y/r82c3gTG/ArYaQy6rIlF/qQ4P4="
    - GIT_NAME="Gini Schorsch"
    - GIT_EMAIL="hello@gini.net" 

script:
  - xcodebuild -workspace Gini-iOS-SDK.xcworkspace -scheme Gini-iOS-SDK -sdk iphonesimulator test
  - xcodebuild -workspace Gini-iOS-SDK.xcworkspace -scheme Documentation -sdk iphonesimulator build
  - ./scripts/integration_tests.sh

after_success:
  - ./scripts/publish_docs.sh

